language: ruby

rvm:
  - 2.5.5

bundler_args: --without production
cache: bundler

services:
  - postgresql

before_script:
  - cp config/database.yml.sample config/database.yml
  - bundle exec rake db:setup

script:
  - bundle exec rspec
  - bundle exec rubocop
  - bundle exec slim-lint app/views
